  version: "3"
  services:
    api:
      build:
        context: .
        dockerfile: Dockerfile.api
      ports:
        - "4000:4000"
      depends_on:
        - mongo

    frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      ports:
        - "80:80"
      depends_on:
        - api

    mongo:
    image: "mongo"  
    ports:
      - "27017:27017"
    environment:
      MONGODB_CONEXION="mongodb+srv://74213068:devLEX077@cluster0.fo41wcf.mongodb.net/tienda?retryWrites=true&w=majority"